name: 💡 Feature Request
description: Suggest an idea or enhancement for this project
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Proposed Feature
      description: Describe the feature you would like to see added.
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: Value / Motivation
      description: Why would this feature be useful to users?
    validations:
      required: true
